In [177]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [178]:
df=sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [179]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [180]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [181]:
X=df.drop('species',axis=1)
y=df['species']

In [182]:
model_knn=KNeighborsClassifier()
model_svm=SVC()

In [183]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
svm_pipeline=Pipeline([('scalar',StandardScaler()),('Classifier',model_svm)])
knn_pipeline = Pipeline([('scaler', StandardScaler()),('knn_classifer', model_knn)])

score_svm=cross_val_score(svm_pipeline, X, y, cv=5)
score_knn=cross_val_score(knn_pipeline, X, y, cv=5)
print(score_svm.mean(),"this is SVM ")
print(score_knn.mean(),"This is KNN")

0.9666666666666666 this is SVM
0.96 This is KNN

In [184]:
#"Grid_search_cv"

In [185]:
from sklearn.model_selection import GridSearchCV
parameter={'Classifier__C':[1,10,20,30],'Classifier__kernel':['linear','rbf'],'Classifier__gamma':['scale','auto']}
grid = GridSearchCV(
    svm_pipeline,
    parameter,
    cv=5,
    return_train_score=True
)
grid.fit(X,y)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('Classifier', SVC())]),
             param_grid={'Classifier__C': [1, 10, 20, 30],
                         'Classifier__gamma': ['scale', 'auto'],
                         'Classifier__kernel': ['linear', 'rbf']},
             return_train_score=True)

In [186]:
print("Best Parameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)

Best Parameters: {'Classifier__C': 10, 'Classifier__gamma': 'scale', 'Classifier__kernel': 'rbf'}
Best Accuracy: 0.9733333333333334

In [187]:
results = pd.DataFrame(grid.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_Classifier__C,param_Classifier__gamma,param_Classifier__kernel,params,split0_test_score,split1_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.007443,0.001395,0.003543,0.000330,1,scale,linear,"{'Classifier__C': 1, 'Classifier__gamma': 'sca...",0.966667,1.000000,...,0.966667,0.029814,3,0.966667,0.966667,0.983333,0.975000,0.966667,0.971667,0.006667
1,0.006224,0.000219,0.003219,0.000168,1,scale,rbf,"{'Classifier__C': 1, 'Classifier__gamma': 'sca...",0.966667,0.966667,...,0.966667,0.021082,9,0.966667,0.975000,0.983333,0.983333,0.966667,0.975000,0.007454
2,0.006682,0.000396,0.003498,0.000241,1,auto,linear,"{'Classifier__C': 1, 'Classifier__gamma': 'aut...",0.966667,1.000000,...,0.966667,0.029814,3,0.966667,0.966667,0.983333,0.975000,0.966667,0.971667,0.006667
3,0.007170,0.001279,0.003474,0.000061,1,auto,rbf,"{'Classifier__C': 1, 'Classifier__gamma': 'aut...",0.966667,0.966667,...,0.966667,0.021082,9,0.966667,0.975000,0.983333,0.983333,0.966667,0.975000,0.007454
4,0.006417,0.000318,0.003204,0.000111,10,scale,linear,"{'Classifier__C': 10, 'Classifier__gamma': 'sc...",1.000000,0.966667,...,0.960000,0.038873,13,0.975000,0.966667,0.991667,0.991667,0.966667,0.978333,0.011304
5,0.006413,0.000479,0.003226,0.000183,10,scale,rbf,"{'Classifier__C': 10, 'Classifier__gamma': 'sc...",1.000000,0.966667,...,0.973333,0.024944,1,0.983333,0.983333,0.991667,0.983333,0.983333,0.985000,0.003333
6,0.006377,0.000742,0.003153,0.000295,10,auto,linear,"{'Classifier__C': 10, 'Classifier__gamma': 'au...",1.000000,0.966667,...,0.960000,0.038873,13,0.975000,0.966667,0.991667,0.991667,0.966667,0.978333,0.011304
7,0.006209,0.000280,0.003176,0.000137,10,auto,rbf,"{'Classifier__C': 10, 'Classifier__gamma': 'au...",1.000000,0.966667,...,0.973333,0.024944,1,0.983333,0.983333,0.991667,0.983333,0.983333,0.985000,0.003333
8,0.006177,0.000376,0.003067,0.000106,20,scale,linear,"{'Classifier__C': 20, 'Classifier__gamma': 'sc...",1.000000,1.000000,...,0.966667,0.042164,9,0.975000,0.966667,0.991667,1.000000,0.975000,0.981667,0.012247
9,0.006453,0.000287,0.003294,0.000167,20,scale,rbf,"{'Classifier__C': 20, 'Classifier__gamma': 'sc...",1.000000,0.966667,...,0.966667,0.029814,3,0.983333,0.983333,0.991667,0.991667,0.983333,0.986667,0.004082
10,0.006037,0.000098,0.003078,0.000028,20,auto,linear,"{'Classifier__C': 20, 'Classifier__gamma': 'au...",1.000000,1.000000,...,0.966667,0.042164,9,0.975000,0.966667,0.991667,1.000000,0.975000,0.981667,0.012247
11,0.006307,0.000221,0.003187,0.000096,20,auto,rbf,"{'Classifier__C': 20, 'Classifier__gamma': 'au...",1.000000,0.966667,...,0.966667,0.029814,3,0.983333,0.983333,0.991667,0.991667,0.983333,0.986667,0.004082
12,0.006985,0.000338,0.003592,0.000446,30,scale,linear,"{'Classifier__C': 30, 'Classifier__gamma': 'sc...",1.000000,1.000000,...,0.960000,0.048990,13,0.975000,0.975000,0.991667,1.000000,0.975000,0.983333,0.010541
13,0.007977,0.001436,0.004427,0.000929,30,scale,rbf,"{'Classifier__C': 30, 'Classifier__gamma': 'sc...",1.000000,0.966667,...,0.966667,0.029814,3,0.983333,0.983333,0.991667,1.000000,0.983333,0.988333,0.006667
14,0.006505,0.000421,0.004359,0.000740,30,auto,linear,"{'Classifier__C': 30, 'Classifier__gamma': 'au...",1.000000,1.000000,...,0.960000,0.048990,13,0.975000,0.975000,0.991667,1.000000,0.975000,0.983333,0.010541
15,0.007409,0.000889,0.003710,0.000304,30,auto,rbf,"{'Classifier__C': 30, 'Classifier__gamma': 'au...",1.000000,0.966667,...,0.966667,0.029814,3,0.983333,0.983333,0.991667,1.000000,0.983333,0.988333,0.006667

In [188]:
results[['param_Classifier__C','param_Classifier__gamma','param_Classifier__kernel','mean_test_score','mean_train_score']]

,param_Classifier__C,param_Classifier__gamma,param_Classifier__kernel,mean_test_score,mean_train_score
0,1,scale,linear,0.966667,0.971667
1,1,scale,rbf,0.966667,0.975000
2,1,auto,linear,0.966667,0.971667
3,1,auto,rbf,0.966667,0.975000
4,10,scale,linear,0.960000,0.978333
5,10,scale,rbf,0.973333,0.985000
6,10,auto,linear,0.960000,0.978333
7,10,auto,rbf,0.973333,0.985000
8,20,scale,linear,0.966667,0.981667
9,20,scale,rbf,0.966667,0.986667
10,20,auto,linear,0.966667,0.981667
11,20,auto,rbf,0.966667,0.986667
12,30,scale,linear,0.960000,0.983333
13,30,scale,rbf,0.966667,0.988333
14,30,auto,linear,0.960000,0.983333
15,30,auto,rbf,0.966667,0.988333

In [189]:
#grid search in kNN
knn_parameter = {
    'knn_classifer__n_neighbors': [3,5,7,9,11],
    'knn_classifer__weights': ['uniform','distance'],
    'knn_classifer__metric': ['euclidean','manhattan']
}

classifier = GridSearchCV(
    knn_pipeline,
    knn_parameter,
    cv=5,
    scoring='accuracy',
    return_train_score=True
)

In [190]:
classifier.fit(X,y)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn_classifer',
                                        KNeighborsClassifier())]),
             param_grid={'knn_classifer__metric': ['euclidean', 'manhattan'],
                         'knn_classifer__n_neighbors': [3, 5, 7, 9, 11],
                         'knn_classifer__weights': ['uniform', 'distance']},
             return_train_score=True, scoring='accuracy')

In [191]:
print("Best Parameters:", classifier.best_params_)
print("Best Accuracy:", classifier.best_score_)
results_knn=pd.DataFrame(classifier.cv_results_)

Best Parameters: {'knn_classifer__metric': 'euclidean', 'knn_classifer__n_neighbors': 7, 'knn_classifer__weights': 'distance'}
Best Accuracy: 0.9666666666666666

In [192]:
results_knn[['param_knn_classifer__metric',	'param_knn_classifer__n_neighbors',	'param_knn_classifer__weights','mean_train_score','mean_test_score'	]]

,param_knn_classifer__metric,param_knn_classifer__n_neighbors,param_knn_classifer__weights,mean_train_score,mean_test_score
0,euclidean,3,uniform,0.960000,0.953333
1,euclidean,3,distance,1.000000,0.953333
2,euclidean,5,uniform,0.960000,0.960000
3,euclidean,5,distance,1.000000,0.960000
4,euclidean,7,uniform,0.965000,0.960000
5,euclidean,7,distance,1.000000,0.966667
6,euclidean,9,uniform,0.963333,0.960000
7,euclidean,9,distance,1.000000,0.966667
8,euclidean,11,uniform,0.958333,0.946667
9,euclidean,11,distance,1.000000,0.960000
10,manhattan,3,uniform,0.960000,0.953333
11,manhattan,3,distance,1.000000,0.953333
12,manhattan,5,uniform,0.961667,0.946667
13,manhattan,5,distance,1.000000,0.946667
14,manhattan,7,uniform,0.958333,0.960000
15,manhattan,7,distance,1.000000,0.953333
16,manhattan,9,uniform,0.955000,0.946667
17,manhattan,9,distance,1.000000,0.946667
18,manhattan,11,uniform,0.961667,0.946667
19,manhattan,11,distance,1.000000,0.953333

In [193]:
from sklearn.model_selection import RandomizedSearchCV

In [194]:
classifier_r = RandomizedSearchCV(
    svm_pipeline,
    parameter,
    cv=5,
    n_iter = 4
)

In [195]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('Classifier', SVC())]),
                   n_iter=4,
                   param_distributions={'Classifier__C': [1, 10, 20, 30],
                                        'Classifier__gamma': ['scale', 'auto'],
                                        'Classifier__kernel': ['linear',
                                                               'rbf']})

In [196]:
results_r=pd.DataFrame(classifier_r.cv_results_)
results_r
#print(len(classifier_r.cv_results_['params']))
#results_r[['params', 'mean_test_score']]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_Classifier__kernel,param_Classifier__gamma,param_Classifier__C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005794,0.001105,0.002929,0.000629,rbf,scale,1,"{'Classifier__kernel': 'rbf', 'Classifier__gam...",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,2
1,0.004063,0.000152,0.002087,0.000029,linear,auto,20,"{'Classifier__kernel': 'linear', 'Classifier__...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,2
2,0.004104,0.000148,0.002209,0.000068,linear,scale,20,"{'Classifier__kernel': 'linear', 'Classifier__...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,2
3,0.004458,0.000144,0.002172,0.000057,rbf,scale,20,"{'Classifier__kernel': 'rbf', 'Classifier__gam...",1.000000,0.966667,0.933333,0.933333,1.0,0.966667,0.029814,1

In [197]:
#"for the KNN"

In [198]:
classifier_knn_r=RandomizedSearchCV(knn_pipeline,knn_parameter,cv=5,n_iter=5,return_train_score=True)

In [199]:
classifier_knn_r.fit(X,y)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('knn_classifer',
                                              KNeighborsClassifier())]),
                   n_iter=5,
                   param_distributions={'knn_classifer__metric': ['euclidean',
                                                                  'manhattan'],
                                        'knn_classifer__n_neighbors': [3, 5, 7,
                                                                       9, 11],
                                        'knn_classifer__weights': ['uniform',
                                                                   'distance']},
                   return_train_score=True)

In [200]:
results_knn_r=pd.DataFrame(classifier_knn_r.cv_results_)
results_knn_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_knn_classifer__weights,param_knn_classifer__n_neighbors,param_knn_classifer__metric,params,split0_test_score,split1_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.004346,0.000338,0.003809,0.000531,uniform,3,manhattan,"{'knn_classifer__weights': 'uniform', 'knn_cla...",0.966667,0.966667,...,0.953333,0.033993,4,0.958333,0.958333,0.966667,0.966667,0.950000,0.96,0.006236
1,0.003855,0.000195,0.003640,0.000520,uniform,5,euclidean,"{'knn_classifer__weights': 'uniform', 'knn_cla...",0.966667,0.966667,...,0.960000,0.024944,1,0.958333,0.958333,0.958333,0.966667,0.958333,0.96,0.003333
2,0.005604,0.001429,0.004503,0.001021,distance,11,euclidean,"{'knn_classifer__weights': 'distance', 'knn_cl...",0.966667,0.966667,...,0.960000,0.024944,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,0.000000
3,0.004493,0.000136,0.003231,0.000054,distance,5,euclidean,"{'knn_classifer__weights': 'distance', 'knn_cl...",0.966667,0.966667,...,0.960000,0.024944,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,0.000000
4,0.004847,0.000662,0.003455,0.000359,distance,3,euclidean,"{'knn_classifer__weights': 'distance', 'knn_cl...",0.966667,0.966667,...,0.953333,0.033993,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,0.000000

In [201]:
print("Best accuracy",classifier.best_score_)
print("Best param",classifier.best_params_)

Best accuracy 0.9666666666666666
Best param {'knn_classifer__metric': 'euclidean', 'knn_classifer__n_neighbors': 7, 'knn_classifer__weights': 'distance'}